# Delete elements

In [1]:
import numpy as np

In [2]:
# We create a rank 1 ndarray 
x = np.array([1, 2, 3, 4, 5])

# We create a rank 2 ndarray
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])

# We print x
print()
print('Original x = ', x)

# We delete the first and last element of x
x = np.delete(x, [0,4])

# We print x with the first and last element deleted
print()
print('Modified x = ', x)

# We print Y
print()
print('Original Y = \n', Y)

# We delete the first row of y
w = np.delete(Y, 0, axis=0)

# We delete the first and last column of y
v = np.delete(Y, [0,2], axis=1)

# We print w
print()
print('w = \n', w)

# We print v
print()
print('v = \n', v)


Original x =  [1 2 3 4 5]

Modified x =  [2 3 4]

Original Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

w = 
 [[4 5 6]
 [7 8 9]]

v = 
 [[2]
 [5]
 [8]]


# Insert elements

In [6]:
# We create a rank 2 ndarray 
Y = np.array([[1,2,3],[7,8,9]])
print(Y)
print()


# We insert a row between the first and last row of y
w = np.insert(Y,1,[4,5,6],axis=0)
print(w)
print()

# We insert a column between the first and last column of y
v = np.insert(Y,1,[4,5],axis=1)
print(v)


[[1 2 3]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 2 3]
 [7 5 8 9]]


# Stack arrays

In [9]:
# We create a rank 1 ndarray 
X = np.array([1,2])

# We create a rank 2 ndarray 
Y = np.array([[3,4],[5,6]])

# We print x
print()
print('x = ', x)

# We print Y
print()
print('Y = \n', Y)

z = np.vstack((Y, X))

w = np.hstack((Y, X.reshape(2,1)))


# We print z
print()
print('z = \n', z)

# We print w
print()
print('w = \n', w)


x =  [1 2 5 6 7]

Y = 
 [[3 4]
 [5 6]]

z = 
 [[3 4]
 [5 6]
 [1 2]]

w = 
 [[3 4 1]
 [5 6 2]]
