# Set operations

In [1]:
import numpy as np

In [ ]:
# We create a rank 1 ndarray
x = np.array([1,2,3,4,5])

# We create a rank 1 ndarray
y = np.array([6,7,2,8,4])

# We print x
print()
print('x = ', x)

# We print y
print()
print('y = ', y)

# We use set operations to compare x and y:
print()
print('The elements that are both in x and y:', np.intersect1d(x,y))
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))
print('All the elements of x and y:',np.union1d(x,y))

# sort function

In [2]:
x = np.random.randint(1,11,size=(10,))

# We print x
print()
print('Original x = ', x)

# We sort x and print the sorted array using sort as a method.
x.sort()

# When we sort in place the original array is changed to the sorted array. To see this we print x again
print()
print('x after sorting:', x)


Original x =  [ 5  3  2 10  2  2  3  1  3  1]

x after sorting: [ 1  1  2  2  2  3  3  3  5 10]


In [3]:
# We create an unsorted rank 2 ndarray
X = np.random.randint(1,11,size=(5,5))

# We print X
print()
print('Original X = \n', X)
print()

# We sort the columns of X and print the sorted array
print()
print('X with sorted columns :\n', np.sort(X, axis = 0))

# We sort the rows of X and print the sorted array
print()
print('X with sorted rows :\n', np.sort(X, axis = 1))


Original X = 
 [[ 6 10  3  2  6]
 [10  5  4  2  5]
 [ 6  8  4  9  8]
 [ 9  6  5  5  2]
 [ 7  6  9  6  3]]


X with sorted columns :
 [[ 6  5  3  2  2]
 [ 6  6  4  2  3]
 [ 7  6  4  5  5]
 [ 9  8  5  6  6]
 [10 10  9  9  8]]

X with sorted rows :
 [[ 2  3  6  6 10]
 [ 2  4  5  5 10]
 [ 4  6  8  8  9]
 [ 2  5  5  6  9]
 [ 3  6  6  7  9]]
